### ISSUE TITLE
Deprecated selector in `solarized-dark-ui/index.less`

### ISSUE THREAD

**Issue by gmcnaught** [rnhmjoj/solarized-dark-ui#24]
In `solarized-dark-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .highlighted.selection .region` => `atom-text-editor.editor .highlighted.selection .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by rnhmjoj** [comment]
I removed the `::shadow` pseudoselector. The `/deep/` however seems to be necessary to apply the scrollbars style.

**Comment by rnhmjoj** [comment]
Fixed in v0.3.2
