### ISSUE TITLE
Multiple deprecation calls

### ISSUE THREAD

**Issue by edgard** [rnhmjoj/solarized-dark-ui#5]
index.less
Use the `atom-workspace` tag instead of the `workspace` class.
Create Issue on solarized-dark-ui repo
Use the `atom-text-editor` tag instead of the `editor` class.
Create Issue on solarized-dark-ui repo
Use the selector `atom-text-editor[mini]` to select mini-editors.
Create Issue on solarized-dark-ui repo
Use the `atom-text-editor` tag instead of the `editor-colors` class.
Create Issue on solarized-dark-ui repo
Use the `atom-pane` tag instead of the `pane` class.
Create Issue on solarized-dark-ui repo
Use the `atom-pane-container` tag instead of the `panes` class.
Create Issue on solarized-dark-ui repo
Use the selector `atom-pane-axis.horizontal` instead of the `pane-row` class.
Create Issue on solarized-dark-ui repo
Use the selector `atom-pane-axis.vertical` instead of the `pane-column` class.
Create Issue on solarized-dark-ui repo
Use the selector `atom-panel.modal` instead of the `overlay` class.
Create Issue on solarized-dark-ui repo
Use the selector `atom-panel` instead of the `tool-panel` class.
Create Issue on solarized-dark-ui repo
Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension. If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.
Create Issue on solarized-dark-ui repo

**Comment by Rnhmjoj** [comment]
I am no longer using atom so I can't work on this anymore. Maybe someone else would like to maintain the theme.
I will be happy to add him as a collaborator.

**Comment by mikeLspohn** [comment]
If no one else is working on this I wouldn't mind pitching in.

**Comment by Rnhmjoj** [comment]
Ok, thanks. You want me to add you as a collaborator?

**Comment by mikeLspohn** [comment]
That would be awesome. Thanks!

**Comment by Rnhmjoj** [comment]
Here you go.

**Comment by barksten** [comment]
This appears to have been fixed but there are no new release since 0.3.0.
@mikeLspohn Can you make a new release with the new PR's included?

**Comment by Rnhmjoj** [comment]
Yes, it was fixed by https://github.com/Rnhmjoj/solarized-dark-ui/commit/8fd5bffa779734cd68ff3bf2ebb6d1253263f73c
However I don't have atom anymore  and I can't publish a new release.
